import React from 'react'
import Head from 'next/head'
import axios from 'axios'
import BlogLayout from '../../components/blog/layout'
import BlogEntry from '../../components/blog/entry'
import Path from '../../components/common/path'

const Blog = ({ blogs, cate, cnt }) => {
  return (
    <div>
      <Head>
        <title>PKK Blog</title>
        <meta name="description" content="Generated by PKK" />
        <link rel="icon" href="/favicon.png?v=2" />
      </Head>
      <Path path=" 블로그" />
      <BlogLayout cate={cate} cnt={cnt}>
        <BlogEntry blogs={blogs} />
      </BlogLayout>
    </div>
  )
}

Blog.getInitialProps = async () => {
  const response = await axios.get('http://localhost:3000/api/blog')
  const { data } = response
  return {
    blogs: data.post,
    cate: data.cate,
    cnt: data.cnt,
  }
}

export default Blog
