import '../styles/globals.css'
import Head from 'next/head'

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
          <title>HJ Blog</title>
          <meta name="description" content="Generated by PKK" />
          <link rel="icon" href="/images/logo2.png" />
      </Head>
      <Component {...pageProps} />
    </>
  )
}

export default MyApp
