import Head from 'next/head'
import React from 'react'
import axios from 'axios'
import HomePage from '../components/home/homePage'
import styles from '../styles/Home.module.css'

const Home = ({ blogs }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>PKK Blog</title>
        <meta name="description" content="Generated by PKK" />
        <link rel="icon" href="/favicon.png?v=2" />
      </Head>
      <HomePage />
    </div>
  )
}

Home.getInitialProps = async () => {
  const response = await axios.get('http://localhost:3000/api/blog')
  const { data } = response
  console.log('data를 보자~ : ', data)
  return {
    blogs: data,
  }
}

export default Home
